from djpcms.tests.test_djpcms import *
from djpcms.tests.test_baseapplication import *
from djpcms.tests.app_views import *
from djpcms.tests.archive_views import *
from djpcms.tests.test_navigation import *
from djpcms.tests.test_urls import *
from djpcms.tests.doc_views import *
from djpcms.tests.uniforms import *
from djpcms.tests.test_plugins import *
from djpcms.tests.test_page import *
from djpcms.tests.test_response import *
from autocomplete import *